### ISSUE TITLE
Unsubscribe hook

### ISSUE THREAD

**Issue by Johnatan85** [DrmagicE/gmqtt#10]
Would it be possible to include an unsubscribe hook to get notified when a client unsubscribes from a topic but does not disconnect?

**Comment by DrmagicE** [comment]
That's a good suggestion. I will add it this weekend. Thanks.

**Comment by DrmagicE** [comment]
https://github.com/DrmagicE/gmqtt/commit/ebba3eb5f7ccd494b46dd6c0ac5031a7bcc91bf9 updated
