### ISSUE TITLE
Why the auth plugin allow empty password permitted

### ISSUE THREAD

**Issue by haowanxing** [DrmagicE/gmqtt#101]
Here the func [Auth.validate](https://github.com/DrmagicE/gmqtt/blob/6bd426a29976ddb08803e44cf08d0f0f535d6ba6/plugin/auth/auth.go#L87)
`
if hashedPassword == "" || password == "" {
		return true, nil	
}
`
dose it a bad logic?

**Comment by DrmagicE** [comment]
You are right. That was a careless mistake. I will fix it later.
