### ISSUE TITLE
MQTT V5 Support ?

### ISSUE THREAD

**Issue by aki29** [DrmagicE/gmqtt#108]
Hi
We use mosquitto_pub to test gmqtt in MQTT V5 protocol.
But the result is as below
Should we need to configure any setting in gmqtt. TKS

$ mosquitto_pub -h my_host_ip  -p 1883 -t 123 -m abcd  -V mqttv5
Error: A network protocol error occurred when communicating with the broker.

**Comment by DrmagicE** [comment]
@aki29 Hi. It is because gmqtt sets an invalid MaximumQoS property in CONNACK packet which cause mosquitto_pub to report "protocol error".   
I use MQTTX to test gmqtt and it seams MQTTX is more tolerant. However,  it is a bug, thanks for reporting this. I will fix it in a few days.

**Comment by aki29** [comment]
Many Thanks
