### ISSUE TITLE
Point-to-point publish mode

### ISSUE THREAD

**Issue by maddie** [DrmagicE/gmqtt#113]
Is it possible to support point-to-point mode where the broker can publish a message only to one or some of the clients, [like in ActiveMQ](https://codenotfound.com/jms-point-to-point-messaging-example-activemq-maven.html)?

**Comment by DrmagicE** [comment]
AFAIK, there is no point-to-point mode in MQTT world, but you can subscribe a unique topic for your client and then send messages to that particular topic to achieve "point-to-point" communication. 
For example, add a client id prefix to the topic and then you can chose either admin api plugin or writing your own to send messages to a particular topic.

**Comment by maddie** [comment]
Yeah, I understand that it's the best way for each client to subscribe to a unique topic, but the thing is that the devices that are connecting to this broker are all using the same topic, and the topic is hardcoded in them, and they are not easily update-able 😂

The broker they used to connect to is ActiveMQ, and they utilize the PTP mode in JMS to achieve the point-to-point messaging.

Or perhaps is there a way to stop a message from being propagated to a certain client in the hooks? I tried to change the topic in the message from OnDelivered hook but that doesn't seem to work.

**Comment by DrmagicE** [comment]
@maddie You can alter the subscription topic and add the client id prefix to it by using `OnSubscribe` hook. 
Here is an example：
```
func (y *yourPlugin) OnSubscribeWrapper(pre server.OnSubscribe) server.OnSubscribe {
	return func(ctx context.Context, client server.Client, req *server.SubscribeRequest) error {
		for _, v := range req.Subscriptions {
			v.Sub.TopicFilter = client.ClientOptions().ClientID + v.Sub.TopicFilter
		}
		return nil
	}
}
```

**Comment by maddie** [comment]
I see, I'll try this approach and report back.

Thanks a lot!

**Comment by maddie** [comment]
Unfortunately it seems that the client only processes data from the original topic, if it's being changed this way then it stops processing 🥲

**Comment by DrmagicE** [comment]
@maddie In the perspective of the subscriber, it will not see any modification of the topic, which means it still thinks it has subscribed to the original topic.  However, the publisher should send to the modified topic to send messages to the subscriber.

**Comment by maddie** [comment]
Hmm, somehow a test client I've written prints the new topic instead, let me see if it's something wrong with my end.

**Comment by DrmagicE** [comment]
@maddie If you look into the details of the MQTT protocol, you will find there is no "topic name" field in SUBACK, which is the ack packet of the SUBSCRIBE packet. So the client will not see the modification done by the server.

**Comment by maddie** [comment]
I guess it's because the topic name is present in the message payload being published, and the client checks for the topic to be the same as the original subscribed topic.

I'm out of ideas now, so I'm gonna try to contact the developer of the client to see if they can do anything.

Closing this for now, thanks!!
