### ISSUE TITLE
下线检测存可能在问题

### ISSUE THREAD

**Issue by zhongjianlong08** [DrmagicE/gmqtt#114]
1 报client_id冲突，实际只有一个client。报冲突的原因是，系统里面有个client连线后删除不了，一直缓存在系统里,下线了也没法清理，换个角度说是下线检测有问题
2 报clientid为空，找不到如何去定位，定位信息少一些
2021-06-18T14:44:46.631+0800    ERROR   server/client.go:273    connection lost {"client_id": "", "error": "connect time out"}
github.com/DrmagicE/gmqtt/server.(*client).setError.func1
        github.com/DrmagicE/gmqtt/server/client.go:273
sync.(*Once).doSlow
        sync/once.go:66
sync.(*Once).Do
        sync/once.go:57
github.com/DrmagicE/gmqtt/server.(*client).setError
        github.com/DrmagicE/gmqtt/server/client.go:271
github.com/DrmagicE/gmqtt/server.(*client).connectWithTimeOut.func1
        github.com/DrmagicE/gmqtt/server/client.go:520
github.com/DrmagicE/gmqtt/server.(*client).connectWithTimeOut
        github.com/DrmagicE/gmqtt/server/client.go:688
github.com/DrmagicE/gmqtt/server.(*client).serve
        github.com/DrmagicE/gmqtt/server/client.go:1459
最新主干代码编译的版本，刚刚试用，还未投入代码分析解决问题

**Comment by DrmagicE** [comment]
可以提供一下复现的方法么？

**Comment by DrmagicE** [comment]
可以提供一下复现的方法么？

**Comment by luohao123** [comment]
遇到了同样的问题，clientid 连上了，但是客户端掉了，然后客户端重练，服务端说存在重复id，其实要么覆盖佬的ID，要么让新的接上。但是直接拒绝连接
