### ISSUE TITLE
有没有开放一个接口存储所有发布的消息？

### ISSUE THREAD

**Issue by qinjinze** [DrmagicE/gmqtt#119]
订阅的主题是变化的，不可能把所有主题都订阅，想存储带有某个字符串的所有主题的消息，或者有没有开放一个接口存储所有发布的消息？以便做进一步过滤存储。
谢谢！

**Comment by DrmagicE** [comment]
可以通过插件实现`OnMsgArrived`钩子，在钩子中过滤和存储你需要的主题

**Comment by qinjinze** [comment]
能否告诉调用哪个包，哪个方法？或者有空的话在B站做视频讲解一下你们产品使用情况。谢谢！

**Comment by DrmagicE** [comment]
@qinjinze 插件的写法可以参考plugin目录，以及插件介绍：https://juejin.cn/post/6908305981923409934
精力有限，感兴趣可以加我qq: 379342542
