### ISSUE TITLE
集群-消息发送后没有收到消息

### ISSUE THREAD

**Issue by LambertDT** [DrmagicE/gmqtt#126]
你好，我已成功部署集群，且可以通过MQTTX工具分别连接集群中的节点，向其中一个节点发送消息，其他节点订阅主题后也可以收到消息。
我通过publish.swagger.json中 v1/publish POST请求集群其中一个节点发送消息
消息如下：
`{
    "topic_name": "testtopic/1",
    "payload": "testMsg",
    "qos": "0"
}`
但集群中的其他节点订阅主题后却没有收到消息。
问：怎么发送集群中都可以收到的消息？

**Comment by DrmagicE** [comment]
@LambertDT sorry..目前还不支持通过接口在集群中发送消息。接口只能在本节点内发布消息。这看起来的确不是很合理..具体怎么实现还需要设计

**Comment by LambertDT** [comment]
如果不能通过接口在集群中发送消息，是否有其他方式可以实现在集群中发送消息？源码查看哪里？

**Comment by DrmagicE** [comment]
@LambertDT 最简单的办法你可以用一个客户端连到集群上然后发消息。 源码的话，可以参考federation插件的相关实现。
https://github.com/DrmagicE/gmqtt/blob/9db2d0ba3bcbc052f1bf090c88c370bcbda61f51/plugin/federation/hooks.go#L178-L195

接口不能触发在集群中发送的原因是通过接口触发的Publish不会调用OnMsgArrived这个钩子函数，所以没办法在集群中广播。
https://github.com/DrmagicE/gmqtt/blob/9db2d0ba3bcbc052f1bf090c88c370bcbda61f51/server/publish_service.go#L9-L13

**Comment by LambertDT** [comment]
能否修改接口来触发OnMsgArrived钩子函数，怎么修改？Thx

**Comment by LambertDT** [comment]
已收到。Go的客户端库：https://github.com/eclipse/paho.mqtt.golang   Thx
