### ISSUE TITLE
hook不生效

### ISSUE THREAD

**Issue by LambertDT** [DrmagicE/gmqtt#128]
你好，我使用gmqtt\examples\hook\main.go测试所有hook（gmqtt\server\hook.go）都没有问题
但当我把hook加到cmd/gmqttd/command/start.go中运行时，某些hook不生效,（如onBasicAuth  onSessionCreated等）
Q：hook不懂，hook不生效原因？是配置问题还是需要添加一些代码？请指教 Thx

start.go文件如下
`	
// NewStartCmd creates a *cobra.Command object for start command.
func NewStartCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "start",
		Short: "Start gmqtt broker",
		Run: func(cmd *cobra.Command, args []string) {
			var err error
			must(err)
			c, err := config.ParseConfig(ConfigFile)
			if os.IsNotExist(err) {
				must(err)
			} else {
				must(err)
			}
			if c.PidFile != "" {
				pid, err := pidfile.New(c.PidFile)
				if err != nil {
					must(fmt.Errorf("open pid file failed: %s", err))
				}
				defer pid.Remove()
			}
			tcpListeners, websockets, err := GetListeners(c)
			must(err)
			l, err := c.GetLogger(c.Log)
			must(err)
			logger = l		
....

hooks := server.Hooks{
				OnAccept:            onAccept,
				OnStop:              onStop,
				OnSubscribe:         onSubscribe,
				OnSubscribed:        onSubscribed,
				OnUnsubscribe:       onUnsubscribe,
				OnUnsubscribed:      onUnsubscribed,
				OnMsgArrived:        onMsgArrived,
				OnBasicAuth:         onBasicAuth,
				OnEnhancedAuth:      onEnhancedAuth,
				OnReAuth:            onReAuth,
				OnConnected:         onConnected,
				OnSessionCreated:    onSessionCreated,
				OnSessionResumed:    onSessionResumed,
				OnSessionTerminated: onSessionTerminated,
				OnDelivered:         onDelivered,
				OnClosed:            onClosed,
				OnMsgDropped:        onMsgDropped,
				OnWillPublish:       onWillPublish,
				OnWillPublished:     onWillPublished,
			}

			s := server.New(
				server.WithConfig(c),
				server.WithTCPListener(tcpListeners...),
				server.WithWebsocketServer(websockets...),
				server.WithLogger(l),
				server.WithHook(hooks),
			)`

**Comment by DrmagicE** [comment]
@LambertDT 不好意思，example可能有点过时了，现在比较推荐的做法是用插件的方式来实现hook方法，插件会把WithHook覆盖掉。具体插件开发可以参考插件开发的文档：https://github.com/DrmagicE/gmqtt/tree/master/plugin

**Comment by LambertDT** [comment]
Thx
