### ISSUE TITLE
报文解析失败后，直接断开是否太严格？

### ISSUE THREAD

**Issue by szmaozi** [DrmagicE/gmqtt#134]
当订阅主题为空字符串时，立刻就会报错。
同时，client被踢掉，不停重连，不停重连不上

问题描述：
如果订阅一个空topic，则会解析失败，进而broker断开client。而如果client实施重连机制，则会一直连接，一直不停断开。

问题解决：
我尝试在`/server/client.go`中调整readLoop函数，如果error为ErrMalformed 则忽略：
```
func (client *client) readLoop() {
    ...
    for {
        ...
		packet, err = client.packetReader.ReadPacket()
		if err != nil {
			if errors.Is(err, codes.ErrMalformed) {
				zaplog.Warn(err.Error())
			} else {
				if err != io.EOF && packet != nil {
					zaplog.Error("read error", zap.String("packet_type", reflect.TypeOf(packet).String()))
				}
				return
			}
		}
        ...
    }
    ...
}
```
这样可以忽略该类错误。但我不清楚会造成什么其他问题影响。
希望可以考虑。

**Comment by DrmagicE** [comment]
这种做法恐怕不妥，ErrMalformed是严重的错误，表示违反MQTT报文规范。在规范文档中，这种错误是需要断开连接的。
参考文档说明：
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718066
> The payload of a SUBSCRIBE packet MUST contain at least one Topic Filter / QoS pair. A SUBSCRIBE packet with no payload is a protocol violation [MQTT-3.8.3-3].

http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718110
> Unless stated otherwise, if either the Server or Client encounters a protocol violation, it MUST close the Network Connection on which it received that Control Packet which caused the protocol violation [MQTT-4.8.0-1].

不光是Subscribe报文会触发ErrMalformed，如果屏蔽了ErrMalformed错误，那这个broker基本不具备识别报文规范错误的能力了。不建议这样做。

一个符合规范的MQTT客户端，不应该订阅空报文。

**Comment by szmaozi** [comment]
明白了。谢谢大佬！
