### ISSUE TITLE
Auth plugin bug

### ISSUE THREAD

**Issue by Farzinkh** [DrmagicE/gmqtt#137]
After uncomment auth from example configuration and adding a account no mqtt client can connect to broker with or without username and password for publish or subscribe and this what actually happen :
`2021-09-18T23:12:23.553+0430	ERROR	server/client.go:273	connection lost	{"client_id": "", "remote_addr": "192.168.43.129:2030", "error": "operation error: Code = 5, reasonString: "}
github.com/DrmagicE/gmqtt/server.(*client).setError.func1
	gmqtt/server/client.go:273
sync.(*Once).doSlow
	/usr/lib/go/src/sync/once.go:68
sync.(*Once).Do
	/usr/lib/go/src/sync/once.go:59
github.com/DrmagicE/gmqtt/server.(*client).setError
	gmqtt/server/client.go:271
github.com/DrmagicE/gmqtt/server.(*client).connectWithTimeOut.func1
	gmqtt/server/client.go:523
github.com/DrmagicE/gmqtt/server.(*client).connectWithTimeOut
	gmqtt/server/client.go:599
github.com/DrmagicE/gmqtt/server.(*client).serve
	gmqtt/server/client.go:1461
`
I just found out that the password was wrong but the log error message is still bizarre

**Comment by DrmagicE** [comment]
@Farzinkh sorry for the late reply.
It works as intended.  `operation error: Code = 5` is the `NotAuthorized` error code in MQTT v3.1.1 protocol.
However, the log here is not clear enough for users. All the error codes are defined as const variables in gmqtt.
> For v3 and v3.1.1 protocol: https://github.com/DrmagicE/gmqtt/blob/master/pkg/codes/codes.go#L12
> For v5 protocol: https://github.com/DrmagicE/gmqtt/blob/master/pkg/codes/codes.go#L26

I think we should also print the related const name rather than just the error code, e.g : `operation error: NotAuthorized(0x05)`
Would you like to help with that？

**Comment by Farzinkh** [comment]
@DrmagicE thanks for your reply.
oh I see thanks for sharing that great links and yes I think since the logs are meant to be human readable it is better to show related const name than just the error code .
Also I have another questions about creating new plugins :

1. why in the examples  directory there is no use of plugins?
2. can we add any kind of plugin to this plugins which are already created ? in my subject I need to add plugin for saving some published messages
3. which database is better for  this desire considering Redis is limited to ram?

**Comment by DrmagicE** [comment]
1. `examples` directory is out-of-date, but I still don't have time to update it, sorry for the confusion. 
2. What do you mean "add any kind of plugin to this plugins which are already created"? If you want to add a new plugin, just do it.  Gmqtt provides a plugin template generator(`gmqctl gen plugin`) which make it very easy to create new plugins.
3. If you mean the persistence of gmqtt, I will suggest using memory instead of Redis. If you mean your plugin, it depends. If you want to persist your published message, then obviously you should use Redis or other backends.

**Comment by Farzinkh** [comment]
About question 2 "plugins which are already created" are what you already developed like auth,federation,... since I tried to add a new one which I created by `gmqctl gen plugin -n <newplugin> -H <some of hooks> -c true -o ./plugin`
and then I tried to add it's name to `default_config.yml` like this:
  - auth
  - prometheus
  - admin
  - federation
  - newplugin
  
  I get this error : 
```
2021-09-22T17:18:44.342+0330	INFO	server/server.go:1112	init plugin hook wrappers
2021-09-22T17:18:44.342+0330	DEBUG	log/log.go:191	2021/09/22 17:18:44 [INFO] serf: EventMemberJoin: farzin-ge602pc 172.18.0.1	{"plugin": "federation"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x92c7f4]

goroutine 1 [running]:
github.com/DrmagicE/gmqtt/server.(*server).initPluginHooks(0xc00011aa80)
	gmqtt/server/server.go:1139 +0xf4
github.com/DrmagicE/gmqtt/server.(*server).init(0xc00011aa80, {0x0, 0x0, 0xb403c0})
	gmqtt/server/server.go:864 +0x8a
github.com/DrmagicE/gmqtt/server.(*server).Init.func1()
	gmqtt/server/server.go:972 +0x32
sync.(*Once).doSlow(0x1, 0x1)
	/usr/lib/go/src/sync/once.go:68 +0xd2
sync.(*Once).Do(...)
	/usr/lib/go/src/sync/once.go:59
github.com/DrmagicE/gmqtt/server.(*server).Init(0xc0001d5920, {0x0, 0x2, 0xc000116130})
	gmqtt/server/server.go:971 +0x7d
github.com/DrmagicE/gmqtt/cmd/gmqttd/command.NewStartCmd.func1(0xc000156000, {0xbf9fc0, 0x2, 0x2})
	gmqtt/cmd/gmqttd/command/start.go:131 +0x4dd
github.com/spf13/cobra.(*Command).execute(0xc000156000, {0xc000132180, 0x2, 0x2})
	/home/farzin/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x11ff4e0)
	/home/farzin/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/home/farzin/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
```
what  am I doing wrong?

**Comment by DrmagicE** [comment]
@Farzinkh you need to append your plugin to `plugin_imports.yml` and then run `go generate ./...` under the project root directory. 
`go generate ./...` will recreate the `plugin.go` file which is needed during compile time. 
> https://github.com/DrmagicE/gmqtt/blob/master/plugin_imports.yml
> https://github.com/DrmagicE/gmqtt/blob/master/cmd/gmqttd/plugins.go

**Comment by Farzinkh** [comment]
@DrmagicE worked like a charm thanks for your help you saved my time . 
maybe it's better to add this step to [How to write plugins](https://github.com/DrmagicE/gmqtt/tree/master/plugin) instruction .

**Comment by DrmagicE** [comment]
@Farzinkh You are right, this important part is missing. Updated.
