### ISSUE TITLE
How to using websocket sever?

### ISSUE THREAD

**Issue by jinfagang** [DrmagicE/gmqtt#141]
Currently I need listen to a tcp url and a  websocket url, what should I do here?

```
ln, err := net.Listen("tcp", c.MQTTConfig.Port)
	ws := &server.WsServer{
		Server: &http.Server{Addr: "127.0.0.1:1885"},
		Path:   v.Websocket.Path,
	}
```

**Comment by DrmagicE** [comment]
@jinfagang Do you mean you wanna use a domain name instead of ip:port?  If so, no further configuration is required by gmqtt.

**Comment by DrmagicE** [comment]
If you need to expose your service to not only the localhost network , use `&http.Server{Addr: "0.0.0.0:1885"}` instead.

**Comment by jinfagang** [comment]
@DrmagicE  how to specific `Path` param? I don't know what Path it need.

**Comment by jinfagang** [comment]
@DrmagicE I try to connect with:

```
	opts := mqtt.NewClientOptions().AddBroker("ws://localhost:1885").SetClientID("fuckitsme_subber")

```

gives me server not response error

**Comment by jinfagang** [comment]
@DrmagicE I found a situation on my server, I can not access any port except 80 on my server, so I can not access any port listen by go, 

then I using nginx for proxy, but I found tcp normally url can not get connect, if I set port to 80.

it give me error:

```
panic: network Error : non-CONNACK first packet received

```

and my mqtt server url is : `mqtt.tsuai.cn` , do u know how should I connect it in such situation?

**Comment by DrmagicE** [comment]
> @DrmagicE how to specific `Path` param? I don't know what Path it need.

@jinfagang `Path` can be defined in the configuration file. If you don't need a specific `Path`, you can just leave it empty and empty string it is also the default value.

**Comment by DrmagicE** [comment]
> @DrmagicE I found a situation on my server, I can not access any port except 80 on my server, so I can not access any port listen by go,
> 
> then I using nginx for proxy, but I found tcp normally url can not get connect, if I set port to 80.
> 
> it give me error:
> 
> ```
> panic: network Error : non-CONNACK first packet received
> ```
> 
> and my mqtt server url is : `mqtt.tsuai.cn` , do u know how should I connect it in such situation?

Why don't just let the gmqtt websocket server listen on port 80?
```
Server: &http.Server{Addr: "0.0.0.0:80"},
```

**Comment by jinfagang** [comment]
@DrmagicE Because not only nginx listen to that port, and I need nginx indeed for another backbone program. They will conflict.

I leaved empty, and listen websocket in 1885, try using `ws://127.0.0.1:1885` to connect, I got:

```
panic: network Error : websocket: bad handshake

```

why?

**Comment by jinfagang** [comment]
![image](https://user-images.githubusercontent.com/21303438/140649310-70780535-ca26-4c38-8fd0-f533cfb186ef.png)

**Comment by DrmagicE** [comment]
> @DrmagicE Because not only nginx listen to that port, and I need nginx indeed for another backend program. They will conflict.
> 
> I leaved empty, and listen websocket in 1885, try using `ws://127.0.0.1:1885` to connect, I got:
> 
> ```
> panic: network Error : websocket: bad handshake
> ```
> 
> why?

@jinfagang It seems your client fails to connect to the socket. I think there may be a configuration error in your setup or your environment.  I tested with the standard entrypoint (`go run cmd/gmqttd . start -c default_config.yml`), and every goes well. 

You can refer to https://github.com/eclipse/paho.mqtt.golang/issues/544

FYI： 
```
// the test code
func main() {
	opts := MQTT.NewClientOptions().AddBroker("ws://localhost:1885")
	client := MQTT.NewClient(opts)
	if token := client.Connect(); token.Wait() && token.Error() != nil {
		panic(token.Error())
	}
	client.Disconnect(250)
}
```

**Comment by jinfagang** [comment]
@DrmagicE the client is exactly same as mine.

But the server, does there anything goes wrong?

```
ln, err := net.Listen("tcp", c.MQTTConfig.Port)
ws := &server.WsServer{
  Server: &http.Server{Addr: "127.0.0.1:1885"},
  Path:   "127.0.0.1:1885",
}
```
Does anything goes wrong? I can't saw there anyting wrong

I don;t know what's config inside your  `go run cmd/gmqttd . start -c default_config.yml` I need listen to tcp and websocket at the same time, does your config really enabled wesbsocket?

**Comment by jinfagang** [comment]
@DrmagicE Besides, your default config listen webscoket port: 8883, how do you able listen with client `ws://localhost:1885`??

```
listeners:
  # bind address
  - address: ":1883"
#    tls:
#      cacert: "path_to_ca_cert_file"
#      cert: "path_to_cert_file"
#      key: "path_to_key_file"

  - address: ":8883"
    # websocket setting
    websocket:
      path: "/"
```

However, I just notic the path in your config is "/". Mine seems wrong?

**Comment by DrmagicE** [comment]
> @DrmagicE Besides, your default config listen webscoket port: 8883, how do you able listen with client `ws://localhost:1885`??
> 
> ```
> listeners:
>   # bind address
>   - address: ":1883"
> #    tls:
> #      cacert: "path_to_ca_cert_file"
> #      cert: "path_to_cert_file"
> #      key: "path_to_key_file"
> 
>   - address: ":8883"
>     # websocket setting
>     websocket:
>       path: "/"
> ```
> 
> However, I just notic the path in your config is "/". Mine seems wrong?

Oops.. I modified the configuration to listen on port 1885:
```

listeners:
  # bind address
  - address: ":1883"
#    tls:
#      cacert: "path_to_ca_cert_file"
#      cert: "path_to_cert_file"
#      key: "path_to_key_file"

  - address: ":1885"
    # websocket setting
    websocket:
      path: "/"
```

Since you are not using the standard entrypoint, I am not sure how you create your configuration. If you are using `config.DefaultConfig()` , the default value is set to "/" automatically.

**Comment by DrmagicE** [comment]
> @DrmagicE the client is exactly same as mine.
> 
> But the server, does there anything goes wrong?
> 
> ```
> ln, err := net.Listen("tcp", c.MQTTConfig.Port)
> ws := &server.WsServer{
>   Server: &http.Server{Addr: "127.0.0.1:1885"},
>   Path:   "127.0.0.1:1885",
> }
> ```
> 
> Does anything goes wrong? I can't saw there anyting wrong
> 
> I don;t know what's config inside your `go run cmd/gmqttd . start -c default_config.yml` I need listen to tcp and websocket at the same time, does your config really enabled wesbsocket?

@jinfagang Please refer to the documentation https://github.com/DrmagicE/gmqtt#get-started, and the sample configuration file here:  https://github.com/DrmagicE/gmqtt/blob/master/cmd/gmqttd/default_config.yml

> The following command will start gmqtt broker with default configuration. The broker listens on 1883 for tcp server and 8883 for websocket server with admin and prometheus plugin loaded.
> 
> $ git clone https://github.com/DrmagicE/gmqtt
> $ cd gmqtt/cmd/gmqttd
> $ go run . start -c default_config.yml

**Comment by DrmagicE** [comment]
@jinfagang Maybe you can refer to the `NewStartCmd()` function: https://github.com/DrmagicE/gmqtt/blob/9bee1682dd2f54199de72736c45d85e3aa21adba/cmd/gmqttd/command/start.go#L97
and compare to your own code to see what's going wrong.

**Comment by jinfagang** [comment]
@DrmagicE My whole configration is using example in your folder:

https://github.com/DrmagicE/gmqtt/blob/master/examples/service/main.go

this is all configration setup:

```
ln, err := net.Listen("tcp", ":1883")
	if err != nil {
		fmt.Println(err.Error())
		return
	}
l, _ := zap.NewDevelopment()
	s := server.New(
		server.WithTCPListener(ln),
		server.WithHook(hooks),
		server.WithLogger(l),
		server.WithConfig(config.DefaultConfig()),
	)
```

I don't want make things complicated, seems default config makes work. So I using it.

But now, I need webscoket listen as well, then I added this thing:

```
ln, err := net.Listen("tcp", c.MQTTConfig.Port)
	ws := &server.WsServer{
		Server: &http.Server{Addr: "127.0.0.1:1885"},
		Path:    "127.0.0.1:1885",
	}
```

Obviously websocket I overrided Path? Or maybe not? that's I want ask....

what should I do simply adding such webscoket listen, I don't need bounch of config files or whatever cmd.... I don't need all things

**Comment by DrmagicE** [comment]
> @jinfagang Maybe you can refer to the `NewStartCmd()` function:
> 
> https://github.com/DrmagicE/gmqtt/blob/9bee1682dd2f54199de72736c45d85e3aa21adba/cmd/gmqttd/command/start.go#L97
> 
> 
> and compare to your own code to see what's going wrong.

I have to say all the stuff is in the source code above and it is not complicated.  If you try to read it I am sure you will figure it out soon. 

After glancing, I think you are missing this line: 
https://github.com/DrmagicE/gmqtt/blob/9bee1682dd2f54199de72736c45d85e3aa21adba/cmd/gmqttd/command/start.go#L127
and try this:
```
ws := &server.WsServer{
		Server: &http.Server{Addr: "127.0.0.1:1885"},
		Path:    "/",
	}
```

Since you are not using the standard entrypoint and the plugin system, I have no knowledge about what is in your program which makes me difficult to help you unless I'm writing the code for you. 

Using gmqtt as a library is possible but required additional knowledge about the codebase.  That is one of the reasons why I recommend users should use the standard entrypoint instead of trying to build their own,  especially when users are not familiar with the codebase or with golang.

**Comment by jinfagang** [comment]
@DrmagicE Obviously I have added this line  server.WithWebsocketServer(websockets...), 

![image](https://user-images.githubusercontent.com/21303438/140699010-a0a204e5-ab52-4c22-ab3f-59a688b0a871.png)

otherwise it can not listen websocket....

what Path effected ? what's different with "/" and "127.0.0.1:1885" in Path??

**Comment by DrmagicE** [comment]
@jinfagang Path represents the HTTP uri. For examples: 
* If path = "/abc", then the websocket address should be ”ws://ip:port/abc“;
* If path = "/", then then the websocket address should be ”ws://ip:port“ or ”ws://ip:port/“

**Comment by jinfagang** [comment]
@DrmagicE what if I set "127.0.0.1:1885", what address should be?

**Comment by DrmagicE** [comment]
@jinfagang ”ws://ip:port127.0.0.1:1885“ should not work. Normally you should set a path with the "/" prefix. It is not about MQTT, it is about HTTP spec.
