### ISSUE TITLE
persistence factory: memory not found

### ISSUE THREAD

**Issue by wwhai** [DrmagicE/gmqtt#142]
```
	logger, _ := zap.NewDevelopment()
	mqttServer := server.New(
		server.WithTCPListener(tcpPort),
		server.WithLogger(logger),
		server.WithConfig(config.DefaultConfig()),
	)
	if err := mqttServer.Run(); err != nil {
		return err
	}
```

**Comment by DrmagicE** [comment]
@wwhai Hi, seems you are facing trouble in using gmqtt as a go package to build your own binary. I suggest you should use gmqtt as an application and leverage the plugin system to custom and extend gmqtt if required.

The example folder is outdated and is going to be removed, sorry for the confusion.

**Comment by wwhai** [comment]
> @wwhai Hi, seems you are facing trouble in using gmqtt as a go package to build your own binary. I suggest you should use gmqtt as an application and leverage the plugin system to custom and extend gmqtt if required.
> 
> The example folder is outdated and is going to be removed, sorry for the confusion.

Yes, I am using gmqtt as a go package to build my own binary. Very thanks for you tell me the reason,

**Comment by gedw99** [comment]
> @wwhai Hi, seems you are facing trouble in using gmqtt as a go package to build your own binary. I suggest you should use gmqtt as an application and leverage the plugin system to custom and extend gmqtt if required.
> 
> The example folder is outdated and is going to be removed, sorry for the confusion.


where are the new examples?

**Comment by DrmagicE** [comment]
@gedw99 Hi, the Get Started session is now the recommended way to run gmqtt. The old examples folder has got many users confused, so I delete it recently.  
Are the [get started](https://github.com/DrmagicE/gmqtt#get-started) session and the [how to write plugins](https://github.com/DrmagicE/gmqtt/blob/master/plugin/README.md) guideline helpful to you?

**Comment by Rebellioncry** [comment]
@DrmagicE  Can't using gmqtt as a go package to build my own binary?If can,how? I just want to use gmqtt as part of my application,gmqtt can't do that?
