### ISSUE TITLE
没看到编译方面的文档

### ISSUE THREAD

**Issue by 547176052** [DrmagicE/gmqtt#146]
windows 怎么编译
linux怎么编译

**Comment by liaoyinyu** [comment]
linux 下运行make 命令应该就可以了

**Comment by DrmagicE** [comment]
@liaoyinyu 感谢回答。 
@547176052 或者更简单点，直接使用go build . 也是可以的。那这个issue我就关闭拉。

**Comment by 547176052** [comment]
好的谢谢
