### ISSUE TITLE
长连接内存耗费很大

### ISSUE THREAD

**Issue by joeevon** [DrmagicE/gmqtt#150]
因为每个客户端连接衍生一个协程，进程内存很大。（5万个连接，占用1.9G内存）
请问这个broker是比较偏向针对短连接吗？

**Comment by DrmagicE** [comment]
@joeevon 你好，设计上没有偏向的，方便的话可以提供一个内存使用情况的pprof截图。看看是否有优化空间。
或者也可以横向对比一下mosquitto和emq看看有多少差距?

ps: gmqtt加上pprof build tag可以开启pprof，如： go run -tags pprof . start -c default_config.yml
默认6060端口。等5w长连接的时候，执行这个命令可以在浏览器看到内存使用情况。
`go tool pprof -http :9090 http://127.0.0.1:6060/debug/pprof/heap`

**Comment by DrmagicE** [comment]
@joeevon
