### ISSUE TITLE
执行的时候报错 没改过库

### ISSUE THREAD

**Issue by paulheguobo** [DrmagicE/gmqtt#153]
..\github.com\DrmagicE\gmqtt\server\api_registrar.go:173:95: unknown field 'OrigName' in struct literal of type runtime.JSONPb
..\github.com\DrmagicE\gmqtt\server\api_registrar.go:173:111: unknown field 'EmitDefaults' in struct literal of type runtime.JSONPb

**Comment by DrmagicE** [comment]
像是grpc-gateway的版本问题。有改过go.mod吗？go版本多少？

**Comment by paulheguobo** [comment]
没改过go.mod go 版本go1.16.2

**Comment by DrmagicE** [comment]
git CI也有用1.16在跑。貌似也没问题。或者再确认下grpc-gateway的版本？
