### ISSUE TITLE
<-client.connected会阻塞吗？

### ISSUE THREAD

**Issue by fatflowers** [DrmagicE/gmqtt#156]
https://github.com/DrmagicE/gmqtt/blob/e45893697645c54cd28b267dfdee8eec4bead207/server/client.go#L421

client.connected只会读出，没有写入的地方，readLoop会卡在这里吗？
![image](https://user-images.githubusercontent.com/4362045/149895446-763d5d2a-a5cc-4d17-8750-a91ab9e3be3a.png)

**Comment by DrmagicE** [comment]
不会，超时会关闭这个channel
