### ISSUE TITLE
出现了一些报错

### ISSUE THREAD

**Issue by LeonScript17** [DrmagicE/gmqtt#163]
老哥你好，我这边使用Gmqtt作为server端，和树莓派4中的HA-mqtt进行通信，然后偶尔会出现这种报错：
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/76414767/161171816-7b0ca4a8-7579-4401-89c7-1d2d358946ac.png">
请问这种报错的原因大概是什么呢？

**Comment by DrmagicE** [comment]
客户端协议可能有错误，服务端解析出错了
https://github.com/DrmagicE/gmqtt/blob/9b6e59706571123da96276a6d57bb0d4e07ae544/pkg/codes/codes.go#L38-L39

**Comment by LeonScript17** [comment]
> 

谢谢您的回复，请问我可以这么理解吗，就是有客户端来向我请求连接，但是尚未到鉴权步骤，其发送过来的请求建立连接的协议就有问题是吗？

**Comment by DrmagicE** [comment]
@LeonScript17 也有可能是鉴权成功之后发来的报文协议异常。

**Comment by LeonScript17** [comment]
我明白了，谢谢您的回复
