### ISSUE TITLE
Any benchmark test data?

### ISSUE THREAD

**Issue by Gypsying** [DrmagicE/gmqtt#174]
Any benchmark test data for gmqtt distributed cluster?

I am curious to know the performance of gmqtt distributed cluster in production environment.
Thanks!

**Comment by DrmagicE** [comment]
@Gypsying Hi, sorry for the late reply. I don't have the benchmark data. 
Actually, the distributed cluster has never been used in production environment, and I have just update the README to clarify.

**Comment by Gypsying** [comment]
Thanks
