### ISSUE TITLE
有没有推荐的golang版本的mqtt客户端和gmqtt一起工作？或者gmqtt有没有计划处一个自己的client库？

### ISSUE THREAD

**Issue by luxiao9999** [DrmagicE/gmqtt#176]
目前mqtt客户端有多种选择，想问问作者一般使用哪个mqtt客户端来测试？

**Comment by DrmagicE** [comment]
可以试试这两个：
https://github.com/eclipse/paho.mqtt.golang
https://chrome.google.com/webstore/detail/mqttbox/kaajoficamnjijhkeomgfljpicifbkaf
