### ISSUE TITLE
websocket packet size over 1024 causing read hang

### ISSUE THREAD

**Issue by Fiekers** [DrmagicE/gmqtt#179]
websocket connection reader implemention will cause read hang

file: server/server.go
line: 1041

```go
func (ws *wsConn) Read(p []byte) (n int, err error) {
	msgType, r, err := ws.c.NextReader()
	if err != nil {
		return 0, err
	}
	if msgType != websocket.BinaryMessage {
		return 0, ErrInvalWsMsgType
	}
	return r.Read(p)
}
```

ws.cNextReader() will close the reader

**Comment by DrmagicE** [comment]
Fixed by https://github.com/DrmagicE/gmqtt/pull/181
Thank you for your contribution.
