### ISSUE TITLE
Sessions does not persist for build in Publish method

### ISSUE THREAD

**Issue by sh0umik** [DrmagicE/gmqtt#18]
I am using this lib for a quite long time. However recently i noticed If i sent message through the gmqtt Publish method and if a client is disconnected at that time the sessions gets lost. When i reconnect i didn't receive the message 

On the other hand, If i send message to topic via a third party client like `paho.mqtt.golang` while the client is disconnected , gmqtt preserves the sessions. Which means when i reconnect i get the published message. 

Please correct me if i am wrong. Is this behaviour suppose to happen ? I am guessing since the build in Publish method of gmqtt does not have a client id so it didn't persist any sessions ? 

Also i am using a plugin approach to re schedule the message from db with the publish method if the gmqtt server gets restarts. I am using the build in publish method for that.

**Comment by DrmagicE** [comment]
This should not happen. To preserve the session or not depends on the CleanSession setting of the client. **Make sure the reconnected client has the same clientID as before, and also keep CleanSession setting to be false**. 

I run the following code with the latest version(master branch):
```
func main() {
	s := gmqtt.DefaultServer()
	// listener
	ln, err := net.Listen("tcp", ":1883")
	if err != nil {
		log.Fatalln(err.Error())
		return
	}
	s.AddTCPListenner(ln)
	ws := &gmqtt.WsServer{
		Server: &http.Server{Addr: ":8080"},
	}
	s.AddWebSocketServer(ws)

	// plugin
	s.AddPlugins(management.New(":9090", nil))

	log.Println("started...")
	s.Run()
	signalCh := make(chan os.Signal, 1)

	go func() {
		for {
			<-time.After(2 * time.Second)
			s.Publish("topic1", []byte("payload"), 0, false)
		}
	}()

	signal.Notify(signalCh, os.Interrupt, syscall.SIGTERM)
	<-signalCh
	s.Stop(context.Background())
	log.Println("stopped")

}
```
and use the following MQTT client tool to test your problem.
https://www.eclipse.org/paho/components/tool/ 

In my test case, the client will receive the message when it reconnects.

**Comment by DrmagicE** [comment]
By the way, there is no client in gmqtt server. The `Publish` method is not a client, it just sends the Publish Packet into a channel and then checks whether there is any matched subscription and delivery the message to matched clients. If any matched client is disconnected and the CleanSession setting is false(which means that the session will be preserved by gmqtt),  the  message will be delivered when the client reconnect with the same clientID and CleanSession = false setting .

**Comment by sh0umik** [comment]
Solved this problem with Client Side `CleanSession ` set to false. When the clients connects and if the sessions is preserved then I got the message. Thx. 

I have few more questions..

Is there anyway to persists all the client sessions ? How do I approach to ReSchedule Message Queue if I restart the gmqtt server ? 

I am thinking about an use case in notifications.

What should be the best approach for that ? Can you guide or share a little bit documentation on implementing my own `sessions.go` with `any key value store like redis` instead of `container/list` package ?

**Comment by DrmagicE** [comment]
According to MQTT protocol, the `CleanSession` flag is on the client side, so the only way to preserve all sessions is to set the `CleanSession` flag for all clients. 

But you can call `Subscribe` method in `onConnected` hook method to resume the subscription for the client. Notice that resuming subscription is not the same as resuming a session, because in MQTT protocol,  the session is more than subscriptions.

What do you mean ReSchedule Message Queue when restart the gmqtt server? 

Gmqtt does not support k/v store for session, it needs a `FIFO` queue to get better performance.

**Comment by DrmagicE** [comment]
> Also i am using a plugin approach to re schedule the message from db with the publish method if the gmqtt server gets restarts. I am using the build in publish method for that.

If you want to publish message when a client connected, using `Publish` method in `onConnected` hook should work.

**Comment by DrmagicE** [comment]
Closed. Feel free to reopen it if you have any further questions.

**Comment by sh0umik** [comment]
No further questions. I have figured out a way to solve my problem using hooks. Thx for the suggestions.
