### ISSUE TITLE
三节点的集群，客户端发送消费二进制数据，节点挂掉了 

### ISSUE THREAD

**Issue by charliexp** [DrmagicE/gmqtt#184]
三节点的集群，一个节点连客户端发送消费二进制数据，另一个客户端连上另一个节点消费数据，发现连消费数据的服务节点挂掉了，log如下：
+0800-12-01 13:16+08:00: 2022-12-01T13:16:12.522+0800   DEBUG   federation/federation.go:502    event ack sent  {"plugin": "federation", "id": 139}
+0800-12-01 13:16+08:00: 2022-12-01T13:16:12.523+0800   ERROR   federation/federation.go:453    EventStream error       {"plugin": "federation", "error": "rpc error: code = Canceled desc = context canceled"}
+0800-12-01 13:16+08:00: github.com/DrmagicE/gmqtt/plugin/federation.(*Federation).EventStream.func1
+0800-12-01 13:16+08:00:        /root/build-proj/gmqtt/plugin/federation/federation.go:453
+0800-12-01 13:16+08:00: github.com/DrmagicE/gmqtt/plugin/federation.(*Federation).EventStream
+0800-12-01 13:16+08:00:        /root/build-proj/gmqtt/plugin/federation/federation.go:513
+0800-12-01 13:16+08:00: github.com/DrmagicE/gmqtt/plugin/federation._Federation_EventStream_Handler
+0800-12-01 13:16+08:00:        /root/build-proj/gmqtt/plugin/federation/federation_grpc.pb.go:335
+0800-12-01 13:16+08:00: google.golang.org/grpc.(*Server).processStreamingRPC
+0800-12-01 13:16+08:00:        /root/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1457
+0800-12-01 13:16+08:00: google.golang.org/grpc.(*Server).handleStream
+0800-12-01 13:16+08:00:        /root/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1537
+0800-12-01 13:16+08:00: google.golang.org/grpc.(*Server).serveStreams.func1.2
+0800-12-01 13:16+08:00:        /root/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:871

**Comment by charliexp** [comment]
发送字符串没有问题，只要发送二进制数据就会发生

**Comment by DrmagicE** [comment]
感谢提交修复
