### ISSUE TITLE
关于mqtts的问题

### ISSUE THREAD

**Issue by hezhuozhuo** [DrmagicE/gmqtt#193]
发现配置文件示例都是在1883端口，如果开启mqtts后，mqtt就无法连接了。是否支持同时开启mqtts和mqtt服务？

**Comment by DrmagicE** [comment]
mqtts和mqtt分别用两个端口

**Comment by hezhuozhuo** [comment]
嗯 是这样的 就是没发现有提示的地方，最后猜对了；配置文件里加个注释就是最好了
