### ISSUE TITLE
你好，有计划开发集群功能么，emq的方式感觉不是很理想。

### ISSUE THREAD

**Issue by azynet1** [DrmagicE/gmqtt#30]

**Comment by DrmagicE** [comment]
有打算，但是估计还没那么快..做完v5开始看集群。mqtt的协议规范导致mqtt的集群模式的确不好做..

**Comment by azynet1** [comment]
> mqtt的协议规范导致mqtt的转化模式的确实不好做。
嗯，我也想过集群，不过一直想不到理想的构架。emq的方式确实实现更方便。
mqtt多用于物联网设备，协议移植繁琐，v5特性并不是太需要，支持上来估计要很久。集群避免单点故障的需求或许会更多。

**Comment by DrmagicE** [comment]
v5基本上做好了，年底差不多能做完，目前已经过了 [paho.mqtt.testing](https://github.com/eclipse/paho.mqtt.testing) 测试，现在还差一些细节优化和单测。 v5兼容v3的。因为我还是打算实现v5的，如果先v3做了集群，再做v5的话改动会比较大..d

**Comment by azynet1** [comment]
哦，这样，多谢了，我在做支持api管理和数据处理持久化的mqtt服务器，会持续关注。

**Comment by DrmagicE** [comment]
感谢关注，欢迎有问题随时讨论。这个issue就先关了哈
