### ISSUE TITLE
例子里面没有接收和发送的demo能不能添加一下呢？

### ISSUE THREAD

**Issue by lx37506** [DrmagicE/gmqtt#32]

**Comment by DrmagicE** [comment]
接收和发送应是客户端的功能，gmqtt是服务端。可以用客户端连上gmqtt来测

**Comment by lx37506** [comment]
我的意思是有没有服务端和web结合起来发送和接收的用例。

**Comment by lx37506** [comment]
我现在想将您的这个gmqtt和gin一起组合起来进行使用。回调的接口全部都测试通过了，现在怎么他们组合在一起进行发送和接收有点不太明白希望能够得到您的指点谢谢！
