### ISSUE TITLE
test: Move test case in trie_db_test.go to test_suite.god

### ISSUE THREAD

**Issue by DrmagicE** [DrmagicE/gmqtt#45]
The test cases located at https://github.com/DrmagicE/gmqtt/blob/v0.2.2/persistence/subscription/mem/trie_db_test.go#L13 should be move to https://github.com/DrmagicE/gmqtt/blob/v0.2.2/persistence/subscription/test/test_suite.go

**Comment by saeidakbari-ir** [comment]
What's the difference between test suite and normal test because what the go coding style says tests should be placed in the same package with the actual codes?

**Comment by DrmagicE** [comment]
The test suite here is used to test the behavior for an interface to ensure the behavior of its implementation is correct. For example, the subscription persistence interface now has 2 implementation, one is memory and one is redis. The test suite will test both memory and redis to ensure the behavior required by the interface is not broken.

**Comment by DrmagicE** [comment]
You can take a look at https://github.com/DrmagicE/gmqtt/blob/master/persistence/memory_test.go and https://github.com/DrmagicE/gmqtt/blob/master/persistence/redis_test.go.  The `TestMemory` and `TestRedis` will run the same test suite, which means I can use one suite to test any further Implementations.

**Comment by DrmagicE** [comment]
Each interface located in the persistence/* package use a test suite to test both `memory` and `redis` implementation.
The tests placed in the same package is also required if you ara testing some low level codes. For example, [topic_trie_test.go](https://github.com/DrmagicE/gmqtt/blob/master/persistence/subscription/mem/topic_trie_test.go) is testing the behavior of the low level data structure for subscription, while the [test_suite.go](https://github.com/DrmagicE/gmqtt/blob/master/persistence/subscription/test/test_suite.go) is testing the behavior of the whole [interface](https://github.com/DrmagicE/gmqtt/blob/master/persistence/subscription/interface.go#L94)

**Comment by saeidakbari-ir** [comment]
Excellent,
This way the reliability of the system will increase.
These descriptions would also be helpful if they are added to the contribution guidline.
