### ISSUE TITLE
[bug] admin plugin can't to publish a message

### ISSUE THREAD

**Issue by icepie** [DrmagicE/gmqtt#48]
OS: Linux Arch
OS ARCH: x64
Gmqtt: upstream

I try to use the http api of admin plugin for publish a message by curl tool like this.
```
$ curl -X POST 127.0.0.1:8083/v1/publish -d '{"topic_name":"a","payload":"test","qos":1}'
{}% 
```

But the topic can not receive the message, and I not use other plugins.

Thank you for your good project!

**Comment by saeidakbari-ir** [comment]
Hi

Could you give us more information on what's the behavior. in my case, everything works fine and the message delivered to subscribers.

**Comment by icepie** [comment]
Thank you my bro!

I just use the admin plugin with the [README.md](https://github.com/DrmagicE/gmqtt/blob/master/plugin/admin/README.md), but the publish function can not be work.




> Hi
> 
> Could you give us more information on what's the behavior. in my case, everything works fine and the message delivered to subscribers.

**Comment by icepie** [comment]
sorry, it work fine when I retry it lol.
