### ISSUE TITLE
func (s *SubscribeRequest) Reject(topicName string, err error) fails to send subscribe error to mqtt.js client

### ISSUE THREAD

**Issue by bo-er** [DrmagicE/gmqtt#56]
## Codes
Here is how I tried to send a subscription error:
```go
req.Reject(topic, &codes.Error{
				Code: codes.NotAuthorized,
				ErrorDetails: codes.ErrorDetails{
					ReasonString: []byte("subscription failure"),
				},
			})
```
This is my mqtt.js file, you can use `node [filename].js` to lunch it as a client.
```js
var mqtt = require('mqtt')
var bcrypt = require('bcrypt');


var user = {
    username: "steve",
    password: "ilovesws"
}
bcrypt.genSalt(10, function (err, salt) {
    if (err) {
        console.log(err)
    };

    bcrypt.hash(user.password, salt, function (err, hash) {
        if (err) {
            console.log(err)
        };
        user.password = hash;
        console.log(hash.length)
    });
});




var client = mqtt.connect('mqtt://localhost:18880', {
    clientId: "coco",
    username: user.username,
    password: user.password,
    protocolVersion: 5,
    resubscribe: false
})


var topic = 'sys/af65764f-54de-464b-aa8e-f9f095f7fa32/327c4a2b-97db-4c78-a2c8-5bf85317f0d1/aps'
client.on('connect', function (connack) {
    console.log('connack is :', connack)
    client.subscribe(topic, function (err, granted) {
        console.log(err, granted)
        if (err) {
            console.log(err)
        }
    })
    // client.publish("sys/af65764f-54de-464b-aa8e-f9f095f7fa32/327c4a2b-97db-4c78-a2c8-5bf85317f0d1/gps", "hello", { qos: 0, properties: { userProperties: { Username: "steve", Password: "123456" } } })
})

client.on('disconnect', function (packet) {
    console.log('断开连接:', packet)
})

client.on('message', function (topic, message) {
    // message is Buffer
    console.log('收到消息:', message.toString())

    client.unsubscribe(topic, function () {
        console.log('取消订阅成功')
        client.end()
    })
})
```
## Unexpected behavior on mqtt.js client

And I get this subscribe callback message:

```js
null [
  {
    topic: 'sys/af65764f-54de-464b-aa8e-f9f095f7fa32/327c4a2b-97db-4c78-a2c8-5bf85317f0d1/aps',
    qos: 135,
    nl: false,
    rap: false,
    rh: 0,
    properties: undefined
  }
]
```
It is from this code snippet's console.log function:
```js
client.subscribe(topic, function (err, granted) {
        console.log(err, granted)
        if (err) {
            console.log(err)
        }
    })
```

## What is expected

I expect an error message but mqtt.js client doesn't appear to receive any,what could be wrong? Anyway thank you for this amazing project, it has saved much of my time.
🙇🏻‍♂️

**Comment by DrmagicE** [comment]
Hi, thanks for sharing all details. 
The subscribe callback message in mqtt.js shows that the `code.NotAuthorized` has been set successfully. (qos: 135). 
I am not sure whether mqtt.js will return an error in this case. To confirm, You can publish a message to that topic and see whether the client can receive the message.

If you want to get `ReasonString` in your callback message, you should set `Request Problem Information` property to 1 in the connect packet properties field.
> see: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901053

But I find only the error returned by `OnSubscribe` callback will be set into suback packet while the error in `SubscribeRequest.Subscriptions` will not, it is a bug, I will fix it latter.

**Comment by bo-er** [comment]
> Hi, thanks for sharing all details.
> The subscribe callback message in mqtt.js shows that the `code.NotAuthorized` has been set successfully. (qos: 135).
> I am not sure whether mqtt.js will return an error in this case. To confirm, You can publish a message to that topic and see whether the client can receive the message.
> 
> If you want to get `ReasonString` in your callback message, you should set `Request Problem Information` property to 1 in the connect packet properties field.
> 
> > see: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901053
> 
> But I find only the error returned by `OnSubscribe` callback will be set into suback packet while the error in `SubscribeRequest.Subscriptions` will not, it is a bug, I will fix it latter.

The client cannot receive the message.
But the ErrorDetails is missing on the client side. And now I know that I can tell a success subscription from a failed one with the help of  `qos code`, if it's more than 2 then it's a failed subscription.
