### ISSUE TITLE
draft benchmark NATS vs gmqtt

### ISSUE THREAD

**Issue by vtolstov** [DrmagicE/gmqtt#6]
Hi, i found you project and try to understand what is the best for simple pub/sub model with guarantied message delivery. Now i'm USE nats streaming, how about gmqtt?
And how can i do HA with it?

**Comment by DrmagicE** [comment]
I think different models have different strengths, it is hard to say which is the best without giving a specific scenario.
The MQTT protocol is extremely simple and lightweight messaging protocol, __designed for constrained devices and low-bandwidth, high-latency or unreliable networks__.
It has been widely used in Internet of Things(IoT), so I would say that the MQTT protocol may be the best model for the IoT world.
Although the NATS and MQTT are all sub/pub model, they are designed for different purposes.
Unfortunately, gmqtt dose not support cluster yet, so it can not provide HA in the current release. 
I'm using supervisor in production environment to manage the gmqtt process to provide a restart mechanism in case of crash (the process has been running continuously for about 6 months).

**Comment by vtolstov** [comment]
@DrmagicE thanks!
