### ISSUE TITLE
你是打算计划开发一个完善的mqtt broker吗？

### ISSUE THREAD

**Issue by lchjczw** [DrmagicE/gmqtt#7]
我之前也是测试，用mosquito做了测试，发现没法做集群，只能用桥的方式，不知道你有没有开发集群的计划

**Comment by DrmagicE** [comment]
现阶段计划主要还是提供完善的开发包…提供二次开发能力。方便定制权限管理之类的功能。计划是有集群的，集群还在构思中… emq也可以集群。你也可以看看emq。

**Comment by lchjczw** [comment]
emq开发技术上不太熟悉，所以没怎么看，权限管理提供接口更好吧，类似mosquito那种，想怎么二开都可以，从SQL到http认证，都可以随便搞，最主要的还是整体框架，撑得起并发才行

**Comment by lchjczw** [comment]
https://github.com/fhmq/hmq，这个也是集群的，好像使用的人说，bug挺多

**Comment by lchjczw** [comment]
https://github.com/fhmq/hmq，这个也是集群的，好像使用的人说，bug挺多

**Comment by DrmagicE** [comment]
管理接口有时候不太灵活..HTTP认证的话。并发高很浪费啊..所以我才弄了这个项目。跑了半年多了还是蛮稳定的，我这个比较轻量，qps测过还可以，自己测的比emq,mosquito高些，但还是得需要开发集群版来保证高可用和连接数..
