### ISSUE TITLE
是否做过压测?

### ISSUE THREAD

**Issue by linxingyang** [DrmagicE/gmqtt#71]
> Gmqtt是用Go语言实现的一个具备灵活灵活扩展能力，高性能的MQTT broker，其完整实现了MQTT V3.1.1和V5协议。

请问做过压测吗？单台服务器能带多少个MQTT客户端呢？然后集群部署（比如10个节点能带多少台）呢？

**Comment by DrmagicE** [comment]
@linxingyang 你好，单机版做过压测，集群版没有做过了。现在手头上没有具体数据了..

**Comment by DrmagicE** [comment]
@linxingyang 单台有做过，集群还没有..不过我现在手头上也没有数据了。可以在你的环境上测一下哈。
有位小哥做了一下对比，单机比emq好，供参考：
> I did a benchmark on gmqtt and amazingly it beat the EMQX on a single node :slightly_smiling_face:
<sub>[View in Slack](https://gmqtt.slack.com/archives/C01JJE7ACMN/p1609433151037200)</sub>

**Comment by linxingyang** [comment]
我看不了slack里面的数据，你可以直接复制相关数据上来吗？

看了一下EMQ的说明，只说情况，也不情况这里单集群的配置、节点数如何。
[emqx README](https://github.com/emqx/emqx/blob/master/README-CN.md)
> EMQ X 3.0 单集群可支持千万级别的 MQTT 并发连接。

**Comment by DrmagicE** [comment]
@linxingyang 不好意思..最近比较忙。slack里面没有写具体数据，我手头上没有环境可以压。要不你先自已压测对比一下？
https://github.com/krylovsk/mqtt-benchmark 我之前是用这个工具压的
