### ISSUE TITLE
	ERROR	server/client.go:242	connection lost	{"client_id": "", "error": "operation error: Code = 1, reasonString: "}

### ISSUE THREAD

**Issue by jackandjack** [DrmagicE/gmqtt#94]

**Comment by DrmagicE** [comment]
@jackandjack Are you using V3 client？Gmqtt currently does not support V3 protocol.

**Comment by yuancpfive** [comment]
@DrmagicE I meet this program also when I use MQTTfx.exe in windows, and I can't find the software is use V3 client. 
How can I do to check the gmqtt?
thanks a lot.

**Comment by DrmagicE** [comment]
@yuancpfive check the protocol version setting of the client in MQTTfx.  Can you provide more information about what operations will cause gmqtt to print this error message?

**Comment by yuancpfive** [comment]
I'm sorry for reply so late. 
My MQTT.fx's version is 1.7.1, and I can not find its support mqtt version too.
In my opinion, MQTT.fx is a common software use for mqtt test, perhaps gmqtt should support this software test.

**Comment by DrmagicE** [comment]
@yuancpfive Please check the MQTT version setting in the MQTT.fx . V3 is not supported currently.
![image](https://user-images.githubusercontent.com/13395096/120583492-ed2d3700-c460-11eb-9ff4-7ff7a4a1c936.png)

**Comment by DrmagicE** [comment]
@yuancpfive gmqtt now supports v3.1 protocol, you can try with the master branch. It should solve your problem.
Feel free to reopen the issue if you still have questions.
